// <auto-generated />
using System;
using LabPat.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabPat.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabPat.Domain.Entities.ExameInsumo", b =>
                {
                    b.Property<int>("TipoExameId")
                        .HasColumnType("int");

                    b.Property<int>("InsumoId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantidadeConsumida")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("TipoExameId", "InsumoId");

                    b.HasIndex("InsumoId");

                    b.ToTable("ExameInsumos");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.HistoricoStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("int");

                    b.Property<int>("StatusAnterior")
                        .HasColumnType("int");

                    b.Property<int>("StatusNovo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlteradoPorId");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("HistoricoStatus");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("QuantidadeMinima")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Laudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EmitidoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmitidoPorId")
                        .HasColumnType("int");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmitidoPorId");

                    b.HasIndex("SolicitacaoId")
                        .IsUnique();

                    b.ToTable("Laudos");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdadeAnos")
                        .HasColumnType("int");

                    b.Property<int?>("IdadeMeses")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PesoKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Raca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoEntradaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPublico")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEstimadaConclusao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoClinica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetodoEntrada")
                        .HasColumnType("int");

                    b.Property<string>("ObservacoesInternas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoExameId")
                        .HasColumnType("int");

                    b.Property<int>("VetSolicitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPublico")
                        .IsUnique();

                    b.HasIndex("PacienteId");

                    b.HasIndex("TipoExameId");

                    b.HasIndex("VetSolicitanteId");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.TemplateLaudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoExameId")
                        .HasColumnType("int");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoExameId");

                    b.ToTable("TemplatesLaudo");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.TipoExame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrazoEstimadoDias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TiposExame");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.VetSolicitante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrmvEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrmvNumero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VetsSolicitantes");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.ExameInsumo", b =>
                {
                    b.HasOne("LabPat.Domain.Entities.Insumo", "Insumo")
                        .WithMany("ExameInsumos")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabPat.Domain.Entities.TipoExame", "TipoExame")
                        .WithMany("ExameInsumos")
                        .HasForeignKey("TipoExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("TipoExame");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.HistoricoStatus", b =>
                {
                    b.HasOne("LabPat.Domain.Entities.Usuario", "AlteradoPor")
                        .WithMany("AlteracoesStatus")
                        .HasForeignKey("AlteradoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabPat.Domain.Entities.Solicitacao", "Solicitacao")
                        .WithMany("Historico")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlteradoPor");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Laudo", b =>
                {
                    b.HasOne("LabPat.Domain.Entities.Usuario", "EmitidoPor")
                        .WithMany("Laudos")
                        .HasForeignKey("EmitidoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabPat.Domain.Entities.Solicitacao", "Solicitacao")
                        .WithOne("Laudo")
                        .HasForeignKey("LabPat.Domain.Entities.Laudo", "SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmitidoPor");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("LabPat.Domain.Entities.Tutor", "Tutor")
                        .WithMany("Pacientes")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Solicitacao", b =>
                {
                    b.HasOne("LabPat.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabPat.Domain.Entities.TipoExame", "TipoExame")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("TipoExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabPat.Domain.Entities.VetSolicitante", "VetSolicitante")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("VetSolicitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("TipoExame");

                    b.Navigation("VetSolicitante");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.TemplateLaudo", b =>
                {
                    b.HasOne("LabPat.Domain.Entities.TipoExame", "TipoExame")
                        .WithMany("Templates")
                        .HasForeignKey("TipoExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoExame");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Insumo", b =>
                {
                    b.Navigation("ExameInsumos");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Solicitacao", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("Laudo");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.TipoExame", b =>
                {
                    b.Navigation("ExameInsumos");

                    b.Navigation("Solicitacoes");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Tutor", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AlteracoesStatus");

                    b.Navigation("Laudos");
                });

            modelBuilder.Entity("LabPat.Domain.Entities.VetSolicitante", b =>
                {
                    b.Navigation("Solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
